# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eCommerce' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eCommerce

  target 'eCommerce-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'eCommerceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'eCommerce-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eCommerce-tvOS

  target 'eCommerce-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
